name: Build LaTeX PDF

on:
  push:
    paths:
      - "resume.tex"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install TeX Live
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-extra

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error resume.tex
          mkdir -p pdf
          mv resume.pdf pdf/resume.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: pdf/resume.pdf

      - name: Commit PDF back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf/resume.pdf
          git commit -m "Add generated PDF" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}